name: mongoid
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowed_failure }}
    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017
    strategy:
      matrix:
        gemfile: [mongoid_5]
        ruby: [2.5.7, 2.6.5]
        allowed_failure: [false]
        include:
          - gemfile: mongoid_6
            ruby: 2.5.7
            allowed_failure: true
          - gemfile: mongoid_7
            ruby: 2.5.7
            allowed_failure: true
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      ADAPTER: mongoid
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: sudo apt-get install -y libsqlite3-dev
      - run: gem update --system
      - run: gem install bundler
      - run: gem --version
      - run: bundle install
      - name: Run Tests
        run: |
          bundle exec rake
